version: "3.8"

services:
  db:
    image: postgres:15
    container_name: taskmanager_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: taskmanager_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
